linters:
  enable:
    - goimports
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - misspell
    - unconvert
    - gocyclo
    - gocritic

linters-settings:
  goimports:
    local-prefixes: github.com/jagreehal/autolemetry-go
  gocyclo:
    min-complexity: 15
